spring:
  cache:
    type: ehcache
    ehcache:
      config: classpath:ehcache.xml

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/pang?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: pang2018!


mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.nit.pang.model.entity

